config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books do
    resources :book_reviews
    resources :book_copies, only: %i[new create]
  end

  resources :book_copies, only: %i[index show destroy] do
    resources :orders, only: %i[new create index] do
      resources :order_reviews, only: %i[create new]
    end
  end

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: :create
  end

  resources :orders do
    member do
      patch "accept"
      patch "reject"
    end
    resources :chatrooms, only: %i[create]
  end

  get "dashboard/:id", to: "pages#dashboard", as: :dashboard
  get "user_profile/:id", to: "user_profiles#show", as: :user_profile
  get "test", to: "pages#test"
end

app/views/shared/_acceptance.html.erb
<div  data-controller="realtime" data-realtime-target="body" class="mb-2 pb-2 d-flex justify-content-between align-items-center">
  <% if order.status == "CREATED" %>

    <%= link_to "Accept", accept_order_path(order), data: {turbo_method: :patch,  action: "click->realtime#send"}, class: "btn btn-info me-1", style: "font-weight: bold; font-size: 14px;"   %>
    <%= link_to "Reject", reject_order_path(order), data: {turbo_method: :patch,  action: "click->realtime#send"}, class: "btn btn-danger me-3", style: "font-weight: bold; font-size: 14px;  color:black;"   %>
    <p class="dashboard-order-status m-0" style="background-color:orange;" ><strong><i class="fa-solid fa-book-open"></i> Requested</strong></p>
  <% elsif order.status == "ACCEPTED"%>

  <%= link_to "Reject", reject_order_path(order), data: {turbo_method: :patch,  action: "click->realtime#send"}, class: "btn btn-danger", style: "font-weight: bold; font-size: 14px;  color:black;" %>
  <p class="dashboard-order-status m-0" style="background-color:lightgreen;"><strong><i class="fa-solid fa-book-open"></i> Accepted</strong></p>
  <% elsif order.status == "REJECTED"%>

    <%= link_to "Re-Accept", accept_order_path(order), data: {turbo_method: :patch, action: "click->realtime#send"},  class: "btn btn-info", style: "font-weight: bold; font-size: 14px; color:black;" %>
    <p class="dashboard-order-status m-0" style="background-color:red"><strong><i class="fa-solid fa-book"></i> Rejected</strong></p>
  <% end %>
</div>

app/views/shared/_backBar.html.erb
<div class="backbar">
 <div class="container-fluid d-flex">
  <%= link_to :back do %>
    <i class="fa-solid fa-arrow-left my-float ms-0" style = "font-size: 20px;"></i>
    <% end %>
    </div>
</div>

app/views/shared/_default_profile_image.html.erb
<%= user.display_name ? user.display_name[0..1].upcase : "#{user.first_name[0].upcase}#{user.last_name[1].upcase}" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_my_book_card.html.erb
<div class="dashboard-my-book-card-container  shadow ps-0">

  <div class= "dashboard-my-book-card  ">


    <%= link_to book_path(book_copy.book_id) do %>
      <%= image_tag book_copy.book.photo_url %>
    <% end %>
    <div class= "dashboard-order-card-description">
      <div>
        <%= link_to book_path(book_copy.book_id) do %>
          <p class="mb-2 dashboard-order-card-title" style = "font-size: 1.25rem; font-weight:bold;"><%= book_copy.book.title %></p>
        <% end %>
      </div>
      <p style = "font-size: 1rem;"><%= book_copy.availability_status %>    <i class="fa-solid fa-euro-sign"></i>  <%= book_copy.availability_status == "Rent" || book_copy.availability_status == "Swap" ? "#{book_copy.price} /day " : "#{book_copy.price} " %></p>
      <% if book_copy.orders.length == 0  %>
        <br>
        <p>You don't have any orders for this book yet.</p>
      <% end %>
      <% if (book_copy.orders.length == 0)  %>
        <div class="d-flex justify-content-between ">
          <%= link_to book_copy_path(book_copy), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"trash-bin" do %>
            <i class="fa-solid fa-trash" ></i>
          <% end %>
        </div>
      <% end %>

    </div>

  </div>

  <% if book_copy.orders.length > 0 %>
    <div class="container pb-1 mb-0 ">
      <% book_copy.orders.each do |order| %>
      <div class="m-0 p-0">
        <hr style="border-top: 1px solid #383232" class="mt-2 mb-2">
            <div class="d-flex align-items-center pb-3 mt-0">
    <div class="pe-2">
      <%= link_to user_profile_path(order.user_id) do %>
        <% if order.user.photo.attached?%>
          <%= cl_image_tag order.user.photo.key, class:"avatar-bordered-medium" %>
        <% else %>
          <div class='avatar-bordered-medium justify-content-center align-items-center' style= " background-color: #75c9b7; " >
            <p style="font-size: 1.5rem; text-align: center;" ><%= render "shared/default_profile_image", user: order.user %></p>
          </div>
        <% end %>
      <% end %>
          </div>
          <div class="justify-content-center d-flex flex-column">
          <%= link_to user_profile_path(order.user_id) do %>
      <p class="normal-link pb-0 m-0" > <%= order.user.display_name || order.user.first_name%> </p>
      <% end %>
      <p class="pb-0 m-0"> <%= order.user.city  %> <%= order.user.country%> </p>
       <p style = "font-size: 1.1rem;" class="mb-0 mt-0"><i class="fa-regular fa-calendar-xmark"></i>
        <% if order.start_date.strftime("%b") == order.end_date.strftime("%b") %>
          <%= order.start_date.strftime("%-d") %> - <%= order.end_date.strftime("%-d") %> <%= order.end_date.strftime(" %b") %>
        <% else %>
          <%= order.start_date.strftime("%-d %b") %> - <%= order.end_date.strftime("%-d %b") %>
        <% end %>
      </p>
      </div>
      </div>

      </div>



      <%= render "shared/acceptance", order: order  %>
      <% end %>
    </div>

  <% end %>


</div>

app/views/shared/_navbar.html.erb
<div class="navbar" data-controller="buttons">
 <%# <%= image_tag "bluelogo.png" %>

        <div class="search">
        <%# <i class="fa fa-search nav-icon"></i> %>


  <%= form_with url: root_path, method: :get, html: { data: { search_books_target: "form"}} do |f| %>

    <%= f.text_field :query,
                  value: params[:query],
                  class: "search-bar",
                  style: "",
                  placeholder: "Find your next book ....",
                  data: {
                    search_books_target: "input",
                    action: "keyup->search-books#update" }
                  %>
</div>


  <div class="book-category-container">
    <div class="filter-button" style="color:#E83E6F">
      <ion-icon name="library" data-buttons-target="allIcon"></ion-icon>
      <%=link_to "All books", root_path %>
    </div>

    <div class="filter-button" data-buttons-target="outerlayer">
      <ion-icon name="skull" data-buttons-target="horrorIcon"></ion-icon>
      <%=link_to "Horror", root_path(:category => "horror"), data: {buttons_target: "horrorbtn"} %>
    </div>

    <div class="filter-button">
      <ion-icon name="planet" data-buttons-target="scifiIcon"></ion-icon>
      <%=link_to "Sci-fi", root_path(:category => "sci-fi"), data: {buttons_target: "scibtn"}%>
    </div>

    <div class="filter-button">
      <ion-icon name="receipt" data-buttons-target="poetryIcon"></ion-icon>
      <%=link_to "Poetry", root_path(:category => "poetry"), data: {buttons_target: "poetrybtn"}%>
    </div>

    <div class="filter-button">
      <ion-icon name="bonfire" data-buttons-target="fictionIcon"></ion-icon>
      <%=link_to "Fiction", root_path(:category => "fiction")%>
    </div>

    <div class="filter-button">
      <ion-icon name="earth" data-buttons-target="travelIcon"></ion-icon>
      <%=link_to "Travel", root_path(:category => "travel")%>
    </div>

    <div class="filter-button">
      <ion-icon name="bulb" data-buttons-target="educationIcon"></ion-icon>
      <%=link_to "Education", root_path(:category => "education")%>
    </div>

    <div class="filter-button">
      <ion-icon name="heart" data-buttons-target="romanceIcon"></ion-icon>
      <%=link_to "Romance", root_path(:category => "romance")%>
    </div>

    <div class="filter-button">
      <ion-icon name="ice-cream" data-buttons-target="comedyIcon"></ion-icon>
      <%=link_to "Comedy", root_path(:category => "comedy")%>
    </div>

    <div class="filter-button">
      <ion-icon name="magnet" data-buttons-target="crimeIcon"></ion-icon>
      <%=link_to "Crime", root_path(:category => "crime")%>
    </div>

  <% end %>
  </div>

</div>

app/views/shared/_navbarBottom.html.erb
<div class="nav-bottom">
  <div class="container-fluid d-flex nav-bottom-item-container">
    <%= link_to root_path, class: "nav-bottom-item" do %>
      <div class="nav-bottom-item">
        <i class="fa fa-home nav-icon"></i>
        <p class="nav-bottom-text">Home</p>
      </div>
    <% end %>
    <%= link_to root_path, class: "nav-bottom-item" do %>
      <div class="nav-bottom-item">
        <i class="fa fa-search nav-icon"></i>
        <p class="nav-bottom-text">Explore</p>
      </div>
    <% end %>
    <% if current_user !=nil %>
    <%= link_to dashboard_path(current_user), class: "nav-bottom-item" do %>
      <div class="nav-bottom-item">
        <i class="fa-solid fa-book-open nav-icon"></i>
        <p class="nav-bottom-text">Books</p>
      </div>
    <% end %>
    <% end %>
    <%= link_to chatrooms_path, class: "nav-bottom-item" do %>
      <div class="nav-bottom-item">
        <i class="fa fa-envelope nav-icon"></i>
        <p class="nav-bottom-text">Inbox</p>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <div class="btn-group dropup">
        <button class="nav-bottom-item justify-content-center" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background: none; border: none;"  >
          <p class="nav-icon p-0 m-0"><i class="fa fa-user nav-icon p-0 m-0"></i></p>
          <p class="nav-bottom-text m-0 p-0">Profile</p>
        </button>
        <div class="dropdown-menu dropdown-menu-begin" >
          <%= link_to "Profile", user_profile_path(current_user.id), class: "dropdown-item"%>
          <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
      <%= link_to new_user_session_path, class: "nav-bottom-item" do %>
        <i class="fa fa-user nav-icon"></i>
        <p class="nav-bottom-text">Login</p>
      <% end %>
    <% end %>
</div>
</div>

app/views/shared/_order_card.html.erb
<div class= "dashboard-order-card shadow">

  <%= link_to book_path(order.book_copy.book_id) do %>
    <%= image_tag order.book_copy.book.photo_url, class: "dashboard-book-img" %>
  <% end %>

  <div class= "dashboard-order-card-description pb-3">
    <%= link_to book_path(order.book_copy.book_id) do %>
      <p class="mb-2 dashboard-order-card-title" style = "font-size: 1.25rem;  font-weight:bold;"><%= order.book_copy.book.title %></p>
    <% end %>

    <div class="d-flex align-items-center justify-content-between mt-2">

      <div class="d-flex justify-content-between mb-3">
        <%= link_to user_profile_path(order.book_copy.user_id) do %>

          <div class="d-flex align-items-center">

            <div class="pe-2">
              <% if order.book_copy.user.photo.attached?%>
                <%= cl_image_tag order.book_copy.user.photo.key, class:"avatar-bordered-medium" %>
              <% else %>
                <div class='avatar-bordered-medium justify-content-center align-items-center' style= " background-color: #75c9b7; " >
                  <p style="font-size: 1.5rem; text-align: center;" ><%= render "shared/default_profile_image", user: order.book_copy.user %></p>
                </div>
              <% end %>
            </div>

            <div class="justify-content-center d-flex flex-column">
              <p  class="normal-link pb-0"> <%= order.book_copy.user.display_name || order.book_copy.user.first_name%></p>
              <p> <%= order.book_copy.user.city  %>, <%= order.book_copy.user.country  %></p>
              <p style = "font-size: 1.1rem;"><i class="fa-regular fa-calendar-xmark"></i>
                <% if order.start_date.strftime("%b") == order.end_date.strftime("%b") %>
                  <%= order.start_date.strftime("%-d") %> - <%= order.end_date.strftime("%-d") %> <%= order.end_date.strftime(" %b") %>
                <% else %>
                  <%= order.start_date.strftime("%-d %b") %> - <%= order.end_date.strftime("%-d %b") %>
                <% end %>
              </p>
            </div>
          </div>
        <% end %>
      </div>

    </div>

    <div class="d-flex justify-content-start flex-column">
      <% if order.status == "CREATED"%>
        <div class="d-flex justify-content-between align-items-center">
          <p class="dashboard-order-status" style="background-color:orange"><strong><i class="fa-solid fa-book-open"></i> Requested</strong></p>
          <%= link_to order_path(order), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"trash-bin" do %>
            <i class="fa-solid fa-trash" ></i>
          <% end %>

        </div>
      <% elsif  order.status == "ACCEPTED"%>

        <p class="dashboard-order-status" style="background-color: lightgreen"><strong><i class="fa-solid fa-book-open"></i> Accepted</strong></p>

        <div class="d-flex justify-content-between mt-3">

          <%= link_to new_book_copy_order_order_review_path(order.book_copy.id, order.id), class:"btn btn-info me-3" do %>
            <div class="btn btn-info p-0 d-flex align-items-center" style= "font-weight: bold; font-size: 14px;"><i class="fa-regular fa-pen-to-square pe-1"></i> Review </div>
          <% end %>

          <% chatroom = Chatroom.find_by(order_id: order.id)%>
          <%= link_to  chatroom_path(chatroom.id), class:"btn btn-info " do   %>
            <div  class="btn btn-info p-0 d-flex align-items-center" style= "font-weight: bold; font-size: 14px;">
              <i class="fa-regular fa-message pe-1"></i> Chat
            </div>
          <% end %>
        </div>
      <% elsif  order.status == "REJECTED"%>
        <p class="dashboard-order-status" style="background-color:orange"><strong><i class="fa-solid fa-book"></i> Rejected </strong></p>
      <% end %>

    </div>


  </div>


</div>

app/views/shared/_rating.html.erb
<% avgrating.to_i.times do |i| %>
  <i class="fa-solid fa-star fa-beat" style="color: #fa8334; font-size: 12px;"></i>
<% end %>

<% if avgrating % 1 != 0 %>
  <i class="fa-solid fa-star-half-stroke fa-beat" style="color: #fa8334; font-size: 12px;"></i>
<% end %>

<% (5-avgrating).to_i.times do |i| %>
  <i class="fa-regular fa-star" style="color: #b2b1b1; font-size: 12px;"></i>
<% end %>

<% if avgrating > 0 %>
  <span class="ms-1 ps-1 pe-1" style="background-color: orange; border-radius: 2px; font-size: 11px;"><%= avgrating.round(1) %></span>
<% end %>