config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books do
    resources :book_reviews
    resources :book_copies, only: %i[new create]
  end

  resources :book_copies, only: %i[index show destroy] do
    resources :orders, only: %i[new create index] do
      resources :order_reviews, only: %i[create new]
    end
  end

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: :create
  end

  resources :orders do
    member do
      patch "accept"
      patch "reject"
    end
    resources :chatrooms, only: %i[create]
  end

  get "dashboard/:id", to: "pages#dashboard", as: :dashboard
  get "user_profile/:id", to: "user_profiles#show", as: :user_profile
  get "test", to: "pages#test"
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_copies, dependent: :destroy
  has_many :book_reviews, dependent: :destroy
  validates :category, presence: true
  validates :year, :pages, numericality: true

  def ribbon(type)
    case type
    when "Greek mythology"
      return "#A790A5"
    when "Horror"
      return "#DD1C1A"
    when "Classic"
      return  "#946846"
    when "Travel"
      return  "#4EA699"
    when "Non-fiction"
      return  "#6E8894"
    when "Romance"
      return  "#E83F6F"
    when "Education"
      return  "#559CAD"
    when "Sci-fi"
      return  "#197BBD"
    when "Fiction"
      return  "#DB8A74"
    when "Poetry"
      return  "#828489"
    when "Crime"
      return  "#F42C04"
    when "Comedy"
      return  "#FE5D26"
    else
      return "#1F7A8C"
    end
  end
end

app/controllers/books_controller.rb
require 'json'
require 'open-uri'

class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show] # Guest user should be able to see the books

  def new
    @book = Book.new
    @book_review = BookReview.new

    set_details_from_api if defined?(params["volumeInfo"]["title"])
  end

  def index
    @search = params[:query]
    search_book(@search) if @search
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @book = Book.find(params[:id])
    @bookreview = BookReview.new
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :description, :pages, :year, :publisher,
                                 :isbn, :category, :language, :photo_url)
  end

  def search_params
    params.require(:book).permit(:query)
  end

  def search_book(search)
    uri = URI("https://www.googleapis.com/books/v1/volumes?q=#{search}&langRestrict=en&key=AIzaSyB0fBuVdMBemt9qqtw4U9uDwzGUptI-SOk")
    results = URI.open(uri).read
    user = JSON.parse(results)
    @books = user["items"]
  end

  def set_details_from_api
    @book.title = params["volumeInfo"]["title"]
    @book.author = params["volumeInfo"]["authors"].nil? ? nil : params["volumeInfo"]["authors"][0]
    @book.description = params["volumeInfo"]["description"]
    @book.pages = params["volumeInfo"]["pageCount"]
    @book.year = params["volumeInfo"]["publishedDate"]
    @book.publisher = params["volumeInfo"]["publisher"]
    @book.isbn = params["volumeInfo"]["industryIdentifiers"].nil? ? nil : params["volumeInfo"]["industryIdentifiers"][0]["identifier"]
    @book.category = params["volumeInfo"]["categories"].nil? ? nil : params["volumeInfo"]["categories"][0]
    @book.language = params["volumeInfo"]["language"]
    @book.photo_url = "https://books.google.com/books/content?id=#{params['id']}&printsec=frontcover&img=1&zoom=1&source=gbs_api"
  end
end

app/views/books/_book_search_form.html.erb
<%= form_with url: books_path, method: :get, class: "d-flex mb-2" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a book"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

app/views/books/_copy_card.html.erb
<div class="book-copy-card">
  <% @book.book_copies.each do |book_copy| %>
    <div class="show-book-copies container mb-0">

      <div class="img-comments pb-2 ">
        <%= link_to user_profile_path(book_copy.user.id) do %>
          <% if book_copy.user.photo.attached?%>
            <%= cl_image_tag book_copy.user.photo.key, class:"avatar-bordered-medium me-2 mt-4"%>
          <% else %>
            <div class='avatar-bordered-medium d-flex justify-content-center align-items-center me-2' style= "padding-right: 9px; background-color: #75c9b7; text-align: center;" >
              <p style="font-size: 2rem text-align: center; text-decoration: none;"><%= render "shared/default_profile_image", user: book_copy.user %></p>
            </div>
          <% end %>
        <% end %>

      <div style="width:100%;">
        <div class="d-flex justify-content-between m-0" >
          <%= link_to user_profile_path(book_copy.user.id) do %>
            <p class="normal-link my-0 ms-0"><%= book_copy.user.display_name %>, <%= book_copy.user.city %> <%= book_copy.user.country %></p>
            <div class="ms-3">
              <%= render "shared/rating", avgrating: OrderReview.where(user_id:  book_copy.user_id).average(:rating) || 0 %>
            </div>
          <% end %>

          <p class="book-category-tag m-0 ms-1" style="font-weight:bold;"><%= book_copy.availability_status %></p>
        </div>

        <% unless book_copy.comments != nil || book_copy.comments == "" %>
          <p class="my-0 mt-2 ms-0"><em>"<%= book_copy.comments.capitalize %>"</em></p>
        <% end %>

        <div class="d-flex   align-items-center">

          <% if user_signed_in? == false || book_copy.user.id != current_user.id %>
            <div class=" justify-content-between">
              <%= link_to  new_book_copy_order_path(book_copy),class:"btn btn-info" do   %>
                <div style="font-size: 12px; font-weight:bold;">
                  <i class="fa-solid fa-cart-shopping"></i> Request
                </div>
              <% end %>
            </div>
          <% end %>

          <p class="me-0" style="font-weight:bold;"><i class="fa-solid fa-euro-sign"></i><%= book_copy.price %> <%= "/ day" unless book_copy.availability_status == "Sell"  %></p>
        </div>
         </div>
      </div>
    </div>
  <% end %>
</div>

app/views/books/_horror.html.erb
<p>top rated books in <span class="horror-text">Horror</span></p>
<div class="book-container">
  <% @horrorbooks.each do |book| %>

    <div class= "book-container-card">
      <div class="front">
      <%= link_to book_path(book) do%>
        <%= image_tag book.photo_url, crop: "fill" %>
      </div>
      <div class="back">

          <div class="ribbon" style="background-color:<%= book.ribbon(book.category) %>">
            <div class="ribbon-text">
              <h6 style="font-size: <%= book.category.length >= 14 ? "10px !important" : "14px !important"   %>" ><%= book.category %></h6>
            </div>
          </div>
          <div class="card-text">
            <h6>- <%= book.author %></h6>
            <h6 style="font-size: <%= book.title.length >= 14 ? "16px !important" : "24px !important"   %>" ><%= book.title %></h6>
          </div>
        <% end %>
      </div>

    </div>
  <% end %>
</div>

app/views/books/_irish.html.erb
<p>Is big brother <span class="brother">Watching you?</span> <%= image_tag "bigbrother.png", height: 40, width: 40  %></p>
<div class="book-container">
  <% @irishbooks.each do |book| %>

    <div class= "book-container-card">
      <div class="front">
      <%= link_to book_path(book) do%>
        <%= image_tag book.photo_url, crop: "fill" %>
      </div>
      <% end %>
          <div class="back">

            <div class="ribbon" style="background-color:<%= book.ribbon(book.category) %>">
              <div class="ribbon-text">
                <h6 style="font-size: <%= book.category.length >= 14 ? "10px !important" : "14px !important"   %>" ><%= book.category %></h6>
              </div>
            </div>
        <div class="card-text">
          <h6>- <%= book.author %></h6>
          <h6 style="font-size: <%= book.title.length >= 14 ? "16px !important" : "24px !important"   %>" ><%= book.title %></h6>
        </div>




        </div>

  </div>
  <% end %>
  </div>

app/views/books/_list.html.erb
<div data-search-books-target="list" data-filter-books-target="book" >
  <div class="book-container">
    <% @books.each do |book| %>

      <div class= "book-container-card">
        <div class="front">
        <%= link_to book_path(book) do%>
            <%= image_tag book.photo_url, crop: "fill"  %>
        </div>
        <div class="back">

            <div class="ribbon" style="background-color:<%= book.ribbon(book.category) %>">
              <div class="ribbon-text">
                <h6 style="font-size: <%= book.category.length >= 14 ? "10px !important" : "14px !important"   %>" ><%= book.category %></h6>
              </div>
            </div>
            <div class="card-text">
              <h6><%= book.author %></h6>
              <h4 style="font-size: <%= book.title.length >= 14 ? "16px !important" : "24px !important"   %>" ><em>"<%= book.title %>"</em></h4>
            </div>
            <div class="d-flex justify-content-center align-items-center">
              <% if book.book_reviews != [] && book.book_reviews.average(:rating) >=4 %>
                <%= render "shared/rating", avgrating: book.book_reviews.average(:rating) || 0 %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

  </div>

</div>

app/views/books/_movie.html.erb
<p>Books that inspired <span class="movie-text">Movies and Tv shows</span></p>
<div class="book-container mb-5 pb-3">
  <% @moviebooks.each do |book| %>

    <div class= "book-container-card">
      <div class="front">
      <%= link_to book_path(book) do%>
        <%= image_tag book.photo_url, crop: "fill" %>
      </div>
      <div class="back">

          <div class="ribbon" style="background-color:<%= book.ribbon(book.category) %>">
            <div class="ribbon-text">
              <h6 style="font-size: <%= book.category.length >= 14 ? "10px !important" : "14px !important"   %>" ><%= book.category %></h6>
            </div>
          </div>
          <div class="card-text">
            <h6>- <%= book.author %></h6>
            <h6 style="font-size: <%= book.title.length >= 14 ? "16px !important" : "24px !important"   %>" ><%= book.title %></h6>
          </div>
        <% end %>
      </div>

    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<%= render "shared/backBar" %>
<div class="container" style="margin-top: 40px;">

  <%= render "books/book_search_form"  %>

  <%= link_to new_book_path, class: "pb-0 mb-3" do  %>
   <p class="pb-0 mt-3 mb-4">If you cannot find your book details below,
   please add your book details from <span class="normal-link mb-3 pb-3" style="text-decoration: underline;"> <i class="fa-solid fa-hand-point-right"></i> here.</span></p>
  <% end %>
  <div class="book-container">

    <% if @books != nil %>
      <% @books.each do |book| %>
        <div class= "book-index-container-card">
            <% @database_book = book["volumeInfo"]["industryIdentifiers"] == nil ? "" : Book.where(isbn: book["volumeInfo"]["industryIdentifiers"][0]["identifier"]).take  %>
          <% if (@database_book == "" || @database_book == nil) %>
            <%= link_to new_book_path (book) do %>
              <%= image_tag "https://books.google.com/books/content?id=#{book['id']}&printsec=frontcover&img=1&zoom=1&source=gbs_api", crop: "fill" %>
              <div class="index-text-container ">
                <h6 class="mb-1 mt-1 ms-1" ><strong><%=  book["volumeInfo"]["title"]%></strong></h6>
                <p class="m-0 ms-1 ps-0" style= "font-size: 12px;"><%= book["volumeInfo"]["authors"].nil? ? nil : book["volumeInfo"]["authors"][0] %></p>
                <p class="m-0 ms-1 ps-0 pb-1" style= "font-size: 12px;"><%=book["volumeInfo"]["industryIdentifiers"].nil? ? nil : "ISBN #{book["volumeInfo"]["industryIdentifiers"][0]["identifier"]}" %></p>

              </div>
            <% end%>

            <% else %>

            <%= link_to book_path (@database_book) do %>
              <%= image_tag @database_book.photo_url, crop: "fill" %>
              <div class="container pt-1 mb-0 pb-1">
                <h6><strong><%=  @database_book.title%></strong></h6>
                <p class="m-0 ms-1 ps-0" style= "font-size: 0.8rem;"><%= @database_book.author%></p>
                <p class="m-0 ms-1 ps-0 pb-1" style= "font-size: 0.8rem;">ISBN <%=@database_book.isbn%></p>
                <%# <p class="m-0 ms-1 ps-0" style= "font-size: 0.8rem;">Category:<%= @database_book.category%></p>
              </div>
            <% end%>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<%= render "shared/backBar" %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-11 col-sm-8 col-md-8 form-login">
    <h2>Add a new book</h2>
    <%= simple_form_for(@book) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%= f.input :title,
                  autofocus: true,
                  input_html: { autocomplete: "title" }%>
        <%= f.input :author,
                  autofocus: true,
                  input_html: { autocomplete: "author" }%>
        <%= f.input :description,
                  autofocus: true,
                  input_html: { autocomplete: "description" }%>
        <%= f.input :pages,
                  autofocus: true,
                  input_html: { autocomplete: "pages" }%>
        <%= f.input :year,
                  autofocus: true,
                  input_html: { autocomplete: "year" }%>
        <%= f.input :publisher,
                  autofocus: true,
                  input_html: { autocomplete: "publisher" }%>
        <%= f.input :isbn,
                  autofocus: true,
                  input_html: { autocomplete: "isbn" }%>
    <%# <% categories = Book.all.map{|t| t.category}.uniq%>
    <%= f.input :category, :collection  => ["Classic", "Comedy", "Crime","Fiction","Greek mythology", "Horror", "Travel","Non-fiction","Romance", "Sci-fi", "Poetry", "Other"] %>
        <%= f.input :language,
                  autofocus: true,
                  input_html: { autocomplete: "language" }%>
        <%= f.input :photo_url,
                  autofocus: true,
                  input_html: { autocomplete: "photo_url" }%>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Add", class: "btn-primary" %>
      </div>
    <% end %>
    </div>
  </div>
</div>



<div class="container">



</div>


        <%# title: book["volumeInfo"]["title"],
        author: book["volumeInfo"]["authors"].nil? ? nil : book["volumeInfo"]["authors"][0],
        description: book["volumeInfo"]["description"],
        pages: book["volumeInfo"]["pageCount"],
        year: book["volumeInfo"]["publishedDate"],
        publisher: book["volumeInfo"]["publisher"],
        isbn: book["volumeInfo"]["industryIdentifiers"].nil? ? nil : book["volumeInfo"]["industryIdentifiers"][0]["identifier"], #tenery operater
        category: book["volumeInfo"]["categories"].nil? ? nil : book["volumeInfo"]["categories"][0],
        language: book["volumeInfo"]["language"],
        photo_url: "https://books.google.com/books/content?id=#{book['id']}&printsec=frontcover&img=1&zoom=1&source=gbs_api") %>

app/views/books/show.html.erb
<%= render "shared/backBar" %>
<div class="container " style="margin-bottom: 130px;">

  <div>
    <%= link_to new_book_book_copy_path(@book), class: "btn btn-primary", style: "opacity: 0.9; position: fixed; bottom: 80px; right:20px;" do %>
    <p class="p-0 m-0"><i class="fa-solid fa-circle-plus"></i> Book Copy </p>
    <% end %>
  </div>

  <h3 class="mb-0 mt-6 pt-4 mt-1 text-center"><strong><%= @book.title %></strong></h3>
  <div class="book-image animate__animated animate__slideInLeft animate__slower mt-3" >
    <%= image_tag @book.photo_url, crop: "fill" %>
  </div>

  <div class="info mt-2">
    <p class="mb-1 mt-0" style="font-weight: bold;"><%= @book.category %><%= " | #{@book.author}" %></p>

    <div class="d-flex justify-content-center align-items-center">


     <%= render "shared/rating", avgrating: @book.book_reviews.average(:rating) || 0 %>

      <%= link_to new_book_book_review_path(@book, @bookreview) do %>
     <div class="ms-2 normal-link" style="text-decoration: underline; font-weight:normal"><%=  " #{@book.book_reviews.count} ratings" if @book.book_reviews.count > 1%> </div>
      <div class="ms-2 normal-link" style="text-decoration: underline; font-weight:normal;"> <%=  " #{@book.book_reviews.count} rating" if @book.book_reviews.count == 1%> </div>
      <% end %>
    </div>

    <div class="mt-2 mb-4">
      <%= link_to new_book_book_review_path(@book, @bookreview), class:"btn btn-info ps-1 pe-1 pt-0 pb-0" do %>
        <p class="btn btn-info p-0 mb-1 mt-1 " style= "font-weight: bold; opacity: 0.7;"><i class="fa-regular fa-pen-to-square"></i> Leave a review</p>
      <% end %>
    </div>
  </div>

      <div class="description"data-controller="read-more" data-read-more-more-text-value="Read more..." data-read-more-less-text-value="Read less">
        <p class="content-1 text-justify" data-read-more-target="content"><%= "\"#{@book.description}\"" if @book.description !=nil &&  @book.description != ""%></p>
        <button class=" normal-link" style="border: none; background:none;" data-action="read-more#toggle">Read more</button>
        <template data-read-more-target="full">
          <p class="content-2 text-justify"><%= "\"#{@book.description}\"" if @book.description !=nil &&  @book.description != ""%></p>

        <% if @book.isbn !=nil &&  @book.isbn != ""%>
          <div class= " d-flex mb-1">
            <p class="show-page-icon-description mb-1 me-3"><i class="fa-solid fa-barcode"></i> ISBN :</p>
            <p class="mb-0 text-center"><%= @book.isbn %></p>
          </div>
        <% end %>


        <% if @book.publisher != nil &&  @book.publisher != "" %>
          <div class= " d-flex mb-1">
            <p class="show-page-icon-description mb-1 me-3"><i class="fa-regular fa-building "></i> Publisher :</p>
            <p class="mb-0 text-center"><%= @book.publisher %></p>
          </div>
        <% end %>

      <% if @book.language !=nil &&  @book.language != ""%>
        <div class= " d-flex mb-1">
          <p class="show-page-icon-description mb-1 me-3"><i class="fa-solid fa-globe "></i> Language :</p>
          <p class="mb-0 text-center"><%= @book.language %></p>
        </div>
      <% end %>

      <% if @book.pages !=nil &&  @book.pages != ""%>
        <div class= " d-flex mb-1">
          <p class="show-page-icon-description mb-1 me-3"><i class="fa-regular fa-file-lines "></i> Pages :</p>
          <p class="mb-0 text-center"><%= @book.pages %></p>
        </div>
      <% end %>

      <% if @book.year !=nil &&  @book.year != ""%>
        <div class= " d-flex mb-1">
          <p class="show-page-icon-description mb-1 me-3"><i class="fa-regular fa-calendar"></i> Year :</p>
          <p class="mb-0 text-center"><%= @book.year %></p>
        </div>
      <% end %>

        </template>
      </div>
        <hr style="border-top: 1px solid #383232">

        <% if @book.book_copies.length == 0  %>
            <p style="font-weight: bold; font-size: 13px;">Sorry we don't have any copies of this book at the moment.<br>
              If you like to share a copy, add from  <%=link_to new_book_book_copy_path(@book) do %>
              <span class="normal-link" style="text-decoration: underline; font-size: 13px;"><i class="fa-solid fa-hand-point-right"></i> here. </span>
              <% end %>
              </p>
        <% else %>
      <h6 style="font-weight: bold;">Following people have copies of this book</h6>
        <% end %>
          <%= render "books/copy_card", books: @books %>

</div>